services:
  api:
    build:
      context: ./docker/
      dockerfile: dev.Dockerfile
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - lems-ya-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lems-ya_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pa5sw@rd
    ports:
      - 5434:5432
    volumes:
      - lems-ya-db:/var/lib/postgresql/data
    networks:
      - lems-ya-network

networks:
  lems-ya-network:
    driver: bridge

volumes:
  lems-ya-db:
    driver: local