// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/cmd/api/server"
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/configs"
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/handlers"
	auth3 "github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/handlers/auth"
	user3 "github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/handlers/user"
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/infrastructure/auth"
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/infrastructure/database"
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/middlewares"
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/repositories/user"
	auth2 "github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/services/auth"
	"github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/services/auth/strategy"
	user2 "github.com/471-68-SE-Classroom/p1-final-project-backend-lems-ya/internal/services/user"
)

// Injectors from wire.go:

func InitializeAPI() *server.EchoServer {
	config := configs.NewConfig()
	db := database.NewPostgrest(config)
	repository := user.NewUserRepository(db)
	localStrategy := strategy.NewLocalStrategy(repository)
	oauth2Config := auth.NewGoogleOAuthClient(config)
	googleStrategy := strategy.NewGoogleStrategy(oauth2Config, repository)
	v := strategy.NewStrategyMap(localStrategy, googleStrategy)
	authService := auth2.NewAuthService(v, repository, config)
	authHandler := auth3.NewAuthHandler(authService, oauth2Config, config)
	userService := user2.NewUserService(repository, config)
	userHandler := user3.NewUserHandler(userService, oauth2Config)
	handlersHandlers := handlers.NewHandlers(authHandler, userHandler)
	authMiddleware := middlewares.NewAuthMiddleware(config)
	echoServer := server.NewEchoServer(config, handlersHandlers, authMiddleware)
	return echoServer
}
