name: Build and Test

on:
  pull_request:
    branches: [develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -coverprofile=coverage.out

      # ❌ Disabled because using SonarCloud Automatic Analysis (free plan)
      # - name: SonarCloud
      #   uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}